### PR TITLE
Pull Request Template

### PR DESCRIPTION
**Pull request by otaviof**
# Changes

Using the same template than other projects in the organization.

# Submitter Checklist

- [ ] ~Includes tests if functionality changed/was added~
- [ ] ~Includes docs if changes are user-facing~
- [x] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [x] Release notes block has been filled in, or marked NONE

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by adambkaplan — APPROVED** [review]
/approve

**Comment by adambkaplan** [comment]
Looks like the e2e test is failing to pull the ko image:

```
+ curl -fsL https://github.com/google/ko/releases/download/null/ko_ull_Linux_x86_64.tar.gz
```

**Comment by otaviof** [comment]
> Looks like the e2e test is failing to pull the ko image:
> 
> ```
> + curl -fsL https://github.com/google/ko/releases/download/null/ko_ull_Linux_x86_64.tar.gz
> ```

It's fixed on #4, we need a newer action to setup `ko` correctly.

**Review by SaschaSchwarze0 — APPROVED** [review]
/lgtm

**Pull request merged**
